title: Hello World!
name: "소프트웨어학과 20223146 조현중"
email: jeclolas@kookmin.ac.kr
description: Super nice life
url: "https://20223146.github.io/"
repository: "20223146.github.io"
github_username: 20223146

# Build settings
theme: minima
plugins:
  - jekyll-feed
