# Setup
title: Jo
tagline: 'A Jekyll theme'
description: My fantastic life
url: http://20223146.github.io
paginate: 5
permalink: pretty

# About/contact
author: A
name: Jo Hyun Joong
url: http://20223146.github.io
email: jeclolas@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
