title: Hello World!
name: "소프트웨어학과 20223143 조원영"
email: reverofmillion@kookmin.ac.kr
description: This is a blog for getting A plus in Eureka Project.
url: "https://20223146.github.io"
repository: "Reveroftrillion/Reveroftrillion.github.io"
twitter_username: I DO NOT USE TWITTER!! Twitter is a waste of time.
github_username:  20223146

# Build settings
theme: minima
plugins:
  - jekyll-feed
